// web/src/views/Filters.vue
<template>
  <div class="filters-container">
    <el-card>
      <template #header>
        <div class="card-header">
          <span>URL过滤规则</span>
          <el-button type="primary" @click="showCreateDialog = true">
            <el-icon><Plus /></el-icon>
            添加规则
          </el-button>
        </div>
      </template>

      <el-table :data="filters" v-loading="loading" style="width: 100%">
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="pattern" label="匹配模式" />
        <el-table-column prop="type" label="类型">
          <template #default="scope">
            <el-tag :type="scope.row.type === 'block' ? 'danger' : 'success'">
              {{ scope.row.type === 'block' ? '阻止' : '允许' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="description" label="描述" />
        <el-table-column prop="enabled" label="状态">
          <template #default="scope">
            <el-tag :type="scope.row.enabled ? 'success' : 'info'">
              {{ scope.row.enabled ? '启用' : '禁用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="created_at" label="创建时间">
          <template #default="scope">
            {{ formatDate(scope.row.created_at) }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200">
          <template #default="scope">
            <el-button size="small" @click="editFilter(scope.row)">编辑</el-button>
            <el-button 
              size="small" 
              type="danger" 
              @click="deleteFilter(scope.row.id)"
            >
              删除
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 创建/编辑过滤规则对话框 -->
    <el-dialog 
      v-model="showCreateDialog" 
      :title="editingFilter ? '编辑过滤规则' : '添加过滤规则'"
      width="500px"
    >
      <el-form :model="filterForm" :rules="rules" ref="filterFormRef" label-width="100px">
        <el-form-item label="匹配模式" prop="pattern">
          <el-input v-model="filterForm.pattern" placeholder="例如: *.google.com" />
        </el-form-item>
        <el-form-item label="类型" prop="type">
          <el-select v-model="filterForm.type" placeholder="选择类型">
            <el-option label="阻止" value="block" />
            <el-option label="允许" value="allow" />
          </el-select>
        </el-form-item>
        <el-form-item label="描述" prop="description">
          <el-input v-model="filterForm.description" type="textarea" />
        </el-form-item>
        <el-form-item label="状态" prop="enabled">
          <el-switch v-model="filterForm.enabled" />
        </el-form-item>
      </el-form>
      <template #footer>
        <span class="dialog-footer">
          <el-button @click="showCreateDialog = false">取消</el-button>
          <el-button type="primary" @click="saveFilter">确定</el-button>
        </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="js">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { useAuthStore } from '@/stores/auth'

const authStore = useAuthStore()
const loading = ref(false)
const filters = ref([])
const showCreateDialog = ref(false)
const editingFilter = ref(null)
const filterFormRef = ref()

const filterForm = ref({
  pattern: '',
  type: 'block',
  description: '',
  enabled: true
})

const rules = {
  pattern: [
    { required: true, message: '请输入匹配模式', trigger: 'blur' }
  ],
  type: [
    { required: true, message: '请选择类型', trigger: 'change' }
  ],
  description: [
    { required: true, message: '请输入描述', trigger: 'blur' }
  ]
}

const fetchFilters = async () => {
  loading.value = true
  try {
    const response = await fetch('/api/v1/filters', {
      headers: {
        'Authorization': `Bearer ${authStore.token}`
      }
    })
    if (response.ok) {
      const data = await response.json()
      filters.value = data.filters
    }
  } catch (error) {
    ElMessage.error('获取过滤规则失败')
  } finally {
    loading.value = false
  }
}

const editFilter = (filter) => {
  editingFilter.value = filter
  filterForm.value = { ...filter }
  showCreateDialog.value = true
}

const saveFilter = async () => {
  if (!filterFormRef.value) return
  
  await filterFormRef.value.validate(async (valid) => {
    if (valid) {
      try {
        const url = editingFilter.value 
          ? `/api/v1/filters/${editingFilter.value.id}`
          : '/api/v1/filters'
        
        const method = editingFilter.value ? 'PUT' : 'POST'
        
        const response = await fetch(url, {
          method,
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${authStore.token}`
          },
          body: JSON.stringify(filterForm.value)
        })
        
        if (response.ok) {
          ElMessage.success(editingFilter.value ? '过滤规则更新成功' : '过滤规则创建成功')
          showCreateDialog.value = false
          fetchFilters()
        }
      } catch (error) {
        ElMessage.error('操作失败')
      }
    }
  })
}

const deleteFilter = async (filterId) => {
  try {
    await ElMessageBox.confirm('确定要删除这个过滤规则吗？', '提示', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })
    
    const response = await fetch(`/api/v1/filters/${filterId}`, {
      method: 'DELETE',
      headers: {
        'Authorization': `Bearer ${authStore.token}`
      }
    })
    
    if (response.ok) {
      ElMessage.success('过滤规则删除成功')
      fetchFilters()
    }
  } catch (error) {
    if (error !== 'cancel') {
      ElMessage.error('删除失败')
    }
  }
}

const formatDate = (date) => {
  return new Date(date).toLocaleString()
}

onMounted(() => {
  fetchFilters()
})
</script>

<style scoped>
.filters-container {
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}
</style>

// web/src/pages/Filters.tsx
import React, { useEffect, useState } from 'react';
import { Table, Button, Modal, Form, Input, Select, Switch, Space, Tag, Popconfirm } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined } from '@ant-design/icons';
import api from '../api/auth';

const { Option } = Select;

interface FilterRule {
  id: number;
  pattern: string;
  type: string;
  description: string;
  enabled: boolean;
  createdAt: string;
}

const Filters: React.FC = () => {
  const [filters, setFilters] = useState<FilterRule[]>([]);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [editingFilter, setEditingFilter] = useState<FilterRule | null>(null);
  const [form] = Form.useForm();

  useEffect(() => {
    fetchFilters();
  }, []);

  const fetchFilters = async () => {
    setLoading(true);
    try {
      const response = await api.get('/filters');
      setFilters(response.filters || []);
    } catch (error) {
      console.error('获取过滤规则失败:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreate = () => {
    setEditingFilter(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleEdit = (record: FilterRule) => {
    setEditingFilter(record);
    form.setFieldsValue({
      pattern: record.pattern,
      type: record.type,
      description: record.description,
      enabled: record.enabled,
    });
    setModalVisible(true);
  };

  const handleDelete = async (id: number) => {
    try {
      await api.delete(`/filters/${id}`);
      fetchFilters();
    } catch (error) {
      console.error('删除过滤规则失败:', error);
    }
  };

  const handleSubmit = async (values: any) => {
    try {
      if (editingFilter) {
        await api.put(`/filters/${editingFilter.id}`, values);
      } else {
        await api.post('/filters', values);
      }
      setModalVisible(false);
      form.resetFields();
      fetchFilters();
    } catch (error) {
      console.error('保存过滤规则失败:', error);
    }
  };

  const columns = [
    {
      title: 'ID',
      dataIndex: 'id',
      key: 'id',
      width: 80,
    },
    {
      title: '匹配模式',
      dataIndex: 'pattern',
      key: 'pattern',
      ellipsis: true,
    },
    {
      title: '类型',
      dataIndex: 'type',
      key: 'type',
      render: (type: string) => (
        <Tag color={type === 'block' ? 'red' : 'green'}>
          {type === 'block' ? '阻止' : '允许'}
        </Tag>
      ),
    },
    {
      title: '描述',
      dataIndex: 'description',
      key: 'description',
      ellipsis: true,
    },
    {
      title: '状态',
      dataIndex: 'enabled',
      key: 'enabled',
      render: (enabled: boolean) => (
        <Tag color={enabled ? 'green' : 'red'}>
          {enabled ? '启用' : '禁用'}
        </Tag>
      ),
    },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => new Date(date).toLocaleString(),
    },
    {
      title: '操作',
      key: 'action',
      render: (_: any, record: FilterRule) => (
        <Space size="middle">
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={() => handleEdit(record)}
          >
            编辑
          </Button>
          <Popconfirm
            title="确定要删除这个过滤规则吗？"
            onConfirm={() => handleDelete(record.id)}
            okText="确定"
            cancelText="取消"
          >
            <Button
              type="link"
              danger
              icon={<DeleteOutlined />}
            >
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div>
      <div style={{ marginBottom: 16 }}>
        <Button
          type="primary"
          icon={<PlusOutlined />}
          onClick={handleCreate}
        >
          添加过滤规则
        </Button>
      </div>

      <Table
        columns={columns}
        dataSource={filters}
        rowKey="id"
        loading={loading}
        pagination={{
          showSizeChanger: true,
          showQuickJumper: true,
          showTotal: (total) => `共 ${total} 条记录`,
        }}
      />

      <Modal
        title={editingFilter ? '编辑过滤规则' : '添加过滤规则'}
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
        width={600}
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
        >
          <Form.Item
            name="pattern"
            label="匹配模式"
            rules={[
              { required: true, message: '请输入匹配模式' },
              { min: 2, message: '匹配模式至少2个字符' },
            ]}
          >
            <Input placeholder="例如: *.google.com 或 192.168.1.*" />
          </Form.Item>

          <Form.Item
            name="type"
            label="规则类型"
            rules={[{ required: true, message: '请选择规则类型' }]}
          >
            <Select>
              <Option value="block">阻止访问</Option>
              <Option value="allow">允许访问</Option>
            </Select>
          </Form.Item>

          <Form.Item
            name="description"
            label="描述"
            rules={[{ max: 200, message: '描述不能超过200个字符' }]}
          >
            <Input.TextArea rows={3} placeholder="可选：添加规则描述" />
          </Form.Item>

          <Form.Item
            name="enabled"
            label="启用状态"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>

          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit">
                {editingFilter ? '更新' : '创建'}
              </Button>
              <Button onClick={() => setModalVisible(false)}>
                取消
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default Filters;
